import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <body
        className={`${inter.variable} min-h-screen h-screen antialiased flex flex-col justify-center items-center `}
      >
        
          {children}
        
        
      </body>
    </html>
  );
}
